version: '3'
services:
  oracle:
    image: oracleinanutshell/oracle-xe-11g
    ports:
      - "1521:1521"
    volumes:
      - oracle_data:/u01/app/oracle
    environment:
      - ORACLE_ALLOW_REMOTE=true
      - ORACLE_DISABLE_ASYNCH_IO=true
volumes:
  oracle_data:
